name: Pre-Merge Checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: # run on request (no need for PR)

jobs:
  Tox:
    runs-on: [self-hosted, linux, x64]
    strategy:
      max-parallel: 1
    steps:
      - name: Print GPU status
        run: nvidia-smi
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v2
      - name: Install Tox
        run: pip install tox
      - name: Code quality checks
        run: tox -e pre-commit
      - name: Coverage
        run: |
          export ANOMALIB_DATASET_PATH=/media/data1/datasets/
          export CUDA_VISIBLE_DEVICES=3
          tox -e pre_merge
      - name: Upload coverage report
        run: |
          # If the workflow is triggered from PR then it gets the commit id from the PR.
          # else it uses the commit id of the latest commit. This is because the commit
          # of the checked-out branch/commit does not exist in the tree as it is grafted.
          if [ -n "${{ github.event.pull_request.head.sha }}" ]
          then
            COMMIT_ID=${{ github.event.pull_request.head.sha }}
          else
            COMMIT_ID=${{ github.sha }}
          fi
          pip install codacy-coverage
          python-codacy-coverage -r .tox/coverage.xml -t ${{ secrets.CODACY }} -c $COMMIT_ID
