dataset:
  name: Tor
  format: one_dimension_packet
  path: ..\anomalib-main\datasets\Tor
  normal_dir: train.csv
  abnormal_dir: test.csv
  normal_test_dir: test.csv
  task: classification
  mask: null
  extensions: null
  split_ratio: null
  image_size: 1600
  train_batch_size: 64
  test_batch_size: 64
  inference_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: false
  tiling:
    apply: true
    tile_size: 64
    stride: null
    remove_border_count: 0
    use_random_tiling: false
    random_tile_count: 16
model:
  name: adversarialflow
  latent_vec_size: 70
  n_features: 16
  extra_layers: 0
  add_final_conv: true
  in_channel: 1
  n_dim: 3430
  lr: 0.001
  lr_flow: 0.001
  lr_generator: 0.001
  lr_discriminator: 0.001
  beta1: 0.5
  beta2: 0.999
  wadv: 1
  wcon: 50
  condition_vector: 0
  coupling_blocks: 8
  clamp_alpha: 1.5
  soft_permutation: false
  mu: 5
  sigmoid: 15
  early_stopping:
    patience: 15
    metric: image_AUROC
    mode: max
  normalization_method: none
metrics:
  image:
  - F1Score
  - AUROC
  - Recall
  - Accuracy
  - Precision
  pixel:
  - F1Score
  - AUROC
  threshold:
    image_default: 0
    adaptive: true
    pixel_default: 0
visualization:
  show_images: false
  save_images: false
  log_images: false
  image_save_path: null
  mode: full
project:
  seed: 42
  path: ./result
logging:
  logger:
  - csv
  log_graph: false
optimization:
  export_mode: null
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 100
  max_steps: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0
